services:
  audiobookarr:
    build: .
    container_name: audiobookarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUDIOBOOKARR_CONFIG=/config
      - AUDIOBOOKARR_AUDIOBOOKS=/audiobooks
      - AUDIOBOOKARR_DOWNLOADS=/downloads
    volumes:
      - ./config:/config
      - /path/to/audiobooks:/audiobooks
      - /path/to/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
